# Generated by Django 4.2.10 on 2024-03-03 01:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IS_app', '0003_subscription_subscription_end_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('video_url', models.URLField()),
                ('publication_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
