# Generated by Django 4.2.10 on 2024-03-05 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IS_app', '0004_post'),
    ]

    operations = [
        migrations.CreateModel(
            name='Scheduler',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.CharField(max_length=200)),
                ('semi_title', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('name', models.TextField()),
                ('time', models.TextField()),
            ],
        ),
    ]
