# Generated by Django 4.2.10 on 2024-03-05 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('IS_app', '0005_scheduler'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduler',
            name='schedule_url',
            field=models.URLField(default=''),
        ),
    ]
